# Base configs
baseurl: "https://gonihalevi.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "goni halevi // 35mm"
subtitle: "take a walk with me"
author: "Goni Halevi"
header:
 title: "35mm"
 subtitle: "by goni halevi"
social_urls:
  instagram: "https://www.instagram.com/film_by_goni"
  github: "https://gonihalevi.github.io"
