# Base configs
baseurl: "https://gonihalevi.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "goni halevi // 35mm"
subtitle: "take a walk with me"
author: "Goni Halevi"
header:
 title: "35mm"
 subtitle: "by goni halevi"
footer:
 name: "hi, thanks for looking at my photos"
 bio: "I shoot with a canon elan and a minolta sr-t 101. some of my favorite film stocks include portra 400, fuji superia, ektar 100, and ilford xp2/hp5."
social_urls:
  instagram: "https://www.instagram.com/film_by_goni"
  github: "https://gonihalevi.github.io"
